#!/usr/bin/env python3
"""
Convert an image into a C array for a supported LAFVIN 4-color e-paper panel.

Output is in the panel's native encoding, so it can be handed straight to
EPD_Display() -- no image2lcd, and no palette remap on the MCU side.

Buffer format (matches EPD_2IN9G_Display / Paint_SetPixel with Scale 4):
  - 2 bits per pixel, 4 pixels per byte, most significant bits first
  - row-major; frame dimensions and byte count depend on --panel
  - color codes: black=0, white=1, yellow=2, red=3

Usage:
  python img2epd.py label.png --panel 2.9 -o img1 --name gImage_img1
  python img2epd.py logo.png --panel 1.54 -o logo --name gImage_logo

Requires Pillow:  pip install Pillow
"""

import argparse
import os
import sys

try:
    from PIL import Image, ImageFilter
except ImportError:
    sys.exit("Pillow is required. Install it with:  pip install Pillow")

PANELS = {
    "2.9": {
        "width": 128,
        "height": 296,
        "default_rotate": 90,
        "description": "2.9-inch 128x296",
    },
    "1.54": {
        "width": 200,
        "height": 200,
        "default_rotate": 0,
        "description": "1.54-inch 200x200",
    },
}

# Panel color codes, and the RGB each one is matched against. The RGB values
# are the idealised primaries -- nearest-neighbour matching maps real artwork
# colors (e.g. a 200,35,35 red) onto the right code without needing exact hits.
PALETTE = [
    ((0, 0, 0), 0),          # black
    ((255, 255, 255), 1),    # white
    ((255, 255, 0), 2),      # yellow
    ((255, 0, 0), 3),        # red
]


def build_quant_image():
    """A 4-entry palette image for Pillow to quantize against."""
    pal = Image.new("P", (1, 1))
    entries = []
    for rgb, _ in PALETTE:
        entries.extend(rgb)
    entries.extend((0, 0, 0) * (256 - len(PALETTE)))
    pal.putpalette(entries)
    return pal


def flatten_to_white(img):
    """Convert transparency to white instead of Pillow's default black."""
    if img.mode in ("RGBA", "LA") or "transparency" in img.info:
        rgba = img.convert("RGBA")
        flattened = Image.new("RGB", rgba.size, (255, 255, 255))
        flattened.paste(rgba, mask=rgba.getchannel("A"))
        return flattened
    return img.convert("RGB")


def fit_image(img, width, height, rotate, sharpen):
    """Resize (and optionally rotate) to the panel's pixel grid.

    Order matters: scale first, then sharpen, then quantize. Sharpening after
    the downscale recovers edges that resampling softens; quantizing last
    keeps intermediate greys from being locked in before they can be sharpened.
    """
    # When rotating, fit the pre-rotation image to the transposed grid so the
    # result lands exactly on WIDTH x HEIGHT.
    if rotate in (90, 270):
        target = (height, width)
    else:
        target = (width, height)

    img = flatten_to_white(img).resize(target, Image.Resampling.LANCZOS)

    if sharpen > 0:
        img = img.filter(ImageFilter.UnsharpMask(radius=1.0,
                                                percent=int(sharpen * 100),
                                                threshold=2))
    if rotate:
        img = img.rotate(-rotate, expand=True)

    if img.size != (width, height):
        img = img.resize((width, height), Image.Resampling.LANCZOS)
    return img


def pack(img, width, height):
    """Quantize to the 4 panel colors and pack 4 pixels per byte, MSB first.

    Dithering is off. This panel is normally driven with flat-color artwork
    (solid text, blocks, logos), where dithering scatters clean edges into
    noise and reads as blur. Nearest-color matching keeps edges crisp.
    """
    quant = img.quantize(
        palette=build_quant_image(), dither=Image.Dither.NONE)
    px = quant.load()

    # Palette index -> panel color code (index order follows PALETTE above).
    code_of = [code for _, code in PALETTE]

    row_bytes = (width + 3) // 4
    frame_bytes = row_bytes * height
    buf = bytearray(frame_bytes)
    for y in range(height):
        row = y * row_bytes
        for x in range(width):
            code = code_of[px[x, y]]
            buf[row + (x >> 2)] |= code << (6 - (x & 3) * 2)
    return buf


def emit_c(buf, name, path, panel_name, width, height):
    frame_bytes = len(buf)
    with open(path, "w", encoding="utf-8") as f:
        f.write("// Generated by tools/img2epd.py -- do not edit by hand.\n")
        f.write("// Panel %s: %d x %d, 2 bits per pixel, panel color codes "
                "(black=0 white=1 yellow=2 red=3).\n"
                "// Ready for EPD_Display(); no palette remap needed.\n\n"
                % (panel_name, width, height))
        f.write("const unsigned char %s[%d] = {\n" % (name, frame_bytes))
        for i in range(0, len(buf), 16):
            chunk = buf[i:i + 16]
            f.write("    " + ",".join("0x%02X" % b for b in chunk) + ",\n")
        f.write("};\n")


def main():
    ap = argparse.ArgumentParser(
        description="Convert an image to a C array for a 4-color EPD.")
    ap.add_argument("image", help="source image (png/jpg/bmp/...)")
    ap.add_argument(
        "--panel", choices=PANELS, default="2.9",
        help="target panel: 2.9=128x296 or 1.54=200x200 (default: 2.9)")
    ap.add_argument("-o", "--out", help="output basename (default: input name)")
    ap.add_argument("--name", help="C array name (default: gImage_<basename>)")
    ap.add_argument("--rotate", type=int, choices=[0, 90, 180, 270],
                    help="clockwise rotation (default: 90 for 2.9, 0 for 1.54)")
    ap.add_argument("--sharpen", type=float, default=1.5,
                    help="unsharp mask strength; 0 disables (default: 1.5)")
    args = ap.parse_args()

    panel = PANELS[args.panel]
    width = panel["width"]
    height = panel["height"]
    rotate = (panel["default_rotate"]
              if args.rotate is None else args.rotate)
    frame_bytes = ((width + 3) // 4) * height

    base = args.out or os.path.splitext(os.path.basename(args.image))[0]
    name = args.name or "gImage_%s" % os.path.basename(base)
    out_c = base if base.endswith(".c") else base + ".c"

    with Image.open(args.image) as source:
        img = fit_image(source, width, height, rotate, args.sharpen)
    buf = pack(img, width, height)
    emit_c(buf, name, out_c, args.panel, width, height)

    print("wrote %s  (%s, rotate=%d, %s[%d])"
          % (out_c, panel["description"], rotate, name, frame_bytes))
    print("declare it with:  extern const unsigned char %s[%d];"
          % (name, frame_bytes))


if __name__ == "__main__":
    main()
